require("raizento.launch")
require("raizento.core.options")
require("raizento.core.keymap")

spec("raizento.plugins.onedark")
spec("raizento.plugins.web-devicons")
--spec("raizento.plugins.treesitter")
--spec("raizento.plugins.autopairs")
spec("raizento.plugins.telescope")
--spec("raizento.plugins.tmux-navigation")
--spec("raizento.plugins.markdown-preview")
--spec("raizento.plugins.cmp")
--spec("raizento.plugins.lualine")
--spec("raizento.plugins.indent-blankline")
--spec("raizento.plugins.gitsigns")
--spec("raizento.plugins.lazygit")
--spec("raizento.plugins.neo-tree")
--spec("raizento.plugins.ufo")
--spec("raizento.plugins.transparent")
--spec("raizento.plugins.which-key")
--spec("raizento.lsp.lsp-plugins")
--spec("raizento.lsp.mason")
--spec("raizento.lsp.lspconfig")
--spec("raizento.plugins.vimtex")
--spec("raizento.plugins.abolish")

require("raizento.lazy")
