require("raizento.util.patches")

require("raizento.launch")
require("raizento.core.options")
require("raizento.core.keymap")

spec("raizento.plugins.onedark")
spec("raizento.plugins.web-devicons")
spec("raizento.plugins.treesitter")
spec("raizento.plugins.tmux-navigation")
spec("raizento.plugins.telescope")
spec("raizento.plugins.autopairs")
spec("raizento.plugins.cmp")
spec("raizento.plugins.lualine")
spec("raizento.plugins.indent-blankline")
spec("raizento.plugins.gitsigns")
spec("raizento.plugins.lazygit")
spec("raizento.plugins.oil")
spec("raizento.plugins.transparent")
spec("raizento.plugins.which-key")

spec("raizento.lsp.lspconfig")
spec("raizento.lsp.mason")
spec("raizento.lsp.plugins.lazydev")
spec("raizento.lsp.plugins.nvim-jdtls")

require("raizento.lazy")
require("raizento.lsp.diagnostic")
require("raizento.lsp.lsp")
